default_platform(:ios)

platform :ios do
  desc "Take App Store screenshots on all required device sizes"
  lane :screenshots do
    snapshot
  end

  desc "Upload screenshots to App Store Connect"
  lane :upload_screenshots do
    deliver(
      skip_binary_upload: true,
      skip_metadata:       true,
      screenshots_path:    "./screenshots",
      overwrite_screenshots: true
    )
  end

  desc "Take screenshots and upload them to App Store Connect in one step"
  lane :screenshots_and_upload do
    snapshot
    deliver(
      skip_binary_upload: true,
      skip_metadata:       true,
      screenshots_path:    "./screenshots",
      overwrite_screenshots: true
    )
  end
end
